export const AGREGAR_CUATRIMESTRE = 'agregarCuatrimestre'
export const ELIMINAR_CUATRIMESTRE = 'eliminarCuatrimestre'
export const EDITAR_FECHA_INICIO = 'editarFechaInicio'
export const EDITAR_FECHA_FIN = 'editarFechaFin'
export const SELECCIONAR_CUATRIMESTRE = 'seleccionarCuatrimestre'
